# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: backend

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-1
  environment:
    DYNAMODB_QUESTIONS_TABLE: ${self:service}-${opt:stage, self:provider.stage}-questions_table
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:PutItem
      Resource:
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_QUESTIONS_TABLE}"


# The `functions` block defines what code to deploy
functions:
  helloWorld:
    handler: handler.helloWorld
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: hello-world
          method: get
          cors: true
  PostQuestionFunction:
    handler: questions.postQuestion
    events:
      - http:
          path: questions
          method: post
          cors: true
  GetQuestionListFunction:
    handler: questions.queryQuestionList
    events:
      - http:
          path: questions
          method: get
          cors: true

resources:  # CloudFormation template syntax
  Resources:
    ServerlessDynamoDbQuestionsTable:
      Type: 'AWS::DynamoDB::Table'
      # DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: category
            AttributeType: S
          - AttributeName: ts
            AttributeType: S
        KeySchema:
          - AttributeName: category
            KeyType: HASH
          - AttributeName: ts
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_QUESTIONS_TABLE}
